name: Test control_toolbox
on:
  pull_request:
  push:
    branches:
      - ros2-master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.1
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros-controls/control_toolbox/ros2-master/control_toolbox.rosinstall
            https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
          package-name: control_toolbox
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          target-ros2-distro: foxy
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
